"""empty message

Revision ID: 7c19b26fbf31
Revises: 
Create Date: 2024-07-26 14:35:15.864428

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7c19b26fbf31'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('auth',
    sa.Column('AUTH_ID', sa.String(), nullable=False),
    sa.Column('AUTH_EXPIRES', sa.Integer(), nullable=False),
    sa.Column('REFRESH_ID', sa.String(), nullable=False),
    sa.Column('member_id', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('PLACEMENT', sa.String(), nullable=False),
    sa.Column('PLACEMENT_OPTIONS', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('member_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('auth')
    # ### end Alembic commands ###
