"""empty message

Revision ID: d45548a55e43
Revises: 
Create Date: 2024-07-27 08:41:39.999576

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd45548a55e43'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('auth',
    sa.Column('access_token', sa.String(), nullable=False),
    sa.Column('expires_in', sa.Integer(), nullable=False),
    sa.Column('refresh_token', sa.String(), nullable=False),
    sa.Column('client_endpoint', sa.String(), nullable=False),
    sa.Column('member_id', sa.String(), nullable=False),
    sa.Column('application_token', sa.String(), nullable=True),
    sa.Column('placement_options', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('member_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('auth')
    # ### end Alembic commands ###
